/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(filtro_FIR_cluster_log.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(77a0a8352c68e99022a85094a32e1f02)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/customModule/filtro_FIR_cluster_log.h>
// pydoc.h is automatically generated in the build directory
#include <filtro_FIR_cluster_log_pydoc.h>

void bind_filtro_FIR_cluster_log(py::module& m)
{

    using filtro_FIR_cluster_log    = gr::customModule::filtro_FIR_cluster_log;


    py::class_<filtro_FIR_cluster_log, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<filtro_FIR_cluster_log>>(m, "filtro_FIR_cluster_log", D(filtro_FIR_cluster_log))

        .def(py::init(&filtro_FIR_cluster_log::make),
           D(filtro_FIR_cluster_log,make)
        )
        



        ;




}








