/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hello_mpi_gnuradio.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(094613627c93cc4ec99f327edaaad75e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/customModule/hello_mpi_gnuradio.h>
// pydoc.h is automatically generated in the build directory
#include <hello_mpi_gnuradio_pydoc.h>

void bind_hello_mpi_gnuradio(py::module& m)
{

    using hello_mpi_gnuradio    = gr::customModule::hello_mpi_gnuradio;


    py::class_<hello_mpi_gnuradio, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<hello_mpi_gnuradio>>(m, "hello_mpi_gnuradio", D(hello_mpi_gnuradio))

        .def(py::init(&hello_mpi_gnuradio::make),
           D(hello_mpi_gnuradio,make)
        )
        



        ;




}








